local addonName, L = ...;

if not (GetLocale() == "deDE") then return end

L["ArenaLive [Spectator] %s"] = "ArenaLive [Spectator] %s"
L["Available Slash Commands for ArenaLive [Spectator] are:"] = "Verfügbare Slashkommandos für ArenaLive [Spectator] sind:"
L["CheckInteractDinstance: %s; CanInspect: %s"] = "CheckInterfaceDistance: %s; CanInspect: %s"
L["CooldownTracker:RegisterUnit(): Usage CooldownTracker:RegisterUnit(unit)"] = "CooldownTracker:RegisterUnit(): Usage CooldodwnTracker:RegisterUnit(unit)"
L["CooldownTracker:UnregisterUnit(): Usage CooldownTracker:UnregisterUnit(unit)"] = "CooldownTracker:UnregisterUnit(): Usage CooldodwnTracker:UnregisterUnit(unit)"
L["|c%s%s|r disconnected."] = "|c%ss%s|r Verbindung wurde unterbrochen."
L["|c%s%s|r is at low health."] = "|c%s%s|r hat wenig Leben."
L["|c%s%s|r reconnected."] = "|c%ss%s|r Verbindung wurde wiederhergestellt."
L["|c%s%s|r tries to resurrect |c%s%s|r."] = "|c%s%s|r versucht |c%s%s|r widerzubeleben."
L["%d:%d"] = "%d:%d"
L["Disable"] = "Ausschalten"
L["%d:%s"] = "%d:%s"
L["Enable Castbar"] = "Zauberleiste aktivieren"
L["Enable Casthistory"] = "Vergangene Zauber anzeigen"
L["Enable Scoreboard"] = "Punktetafel aktivieren"
L["Follow Target"] = "Ziel verfolgen"
L["Gather Cooldown info for %s: GUID = %s, isPlayer = %s, isInspectReady = %s."] = "Sammle Abklingzeitinformation für %s: GUID = %s, isPlayer = %s, isInspectReady = %s."
L["Hide normal UI"] = "Verstecke normale Benutzeroberfläche"
L["Hiding CooldownTracker's handler frame..."] = "Verstecke Abklingzeitverfolgungshandlerframe..."
L["If checked, ArenaLive will fixate the camera on your current target. Note: When following a player, nameplates are disabled by the WoW client."] = "Wenn diese Option gewählt ist, fixiert ArenaLive die Kamera auf das momentane Ziel. Hinweis: Wenn einen Spieler gefolgt wird, werden die Namensplaketten durch den WoW-Client deaktiviert."
L["If checked, a scoreboard with match timer, team name, team score and dampening tracker will be shown during matches."] = "Wenn diese Option aktiviert ist, wird eine Punktetafel mit Spielzeit, Teamnamen, Punkten und einer Dämpfungsanzeige angezeigt."
L["If checked, target and target-of-target frames will be disabled and the width of the current target's side frame will be increased dynamically instead."] = "Wenn diese Option aktiviert ist, werden das Ziel und das Ziel-des-Ziels ausgeblendet und stattdessen wird die Größe des Seitenframes dynamisch angepasst, der das momentane Ziel anzeigt."
L["If enabled, spell tooltips will be shown when moving the mouse over a cooldown button."] = "Wenn diese Option aktiviert ist, werden Zauberinformationen für die Abklinganzeige eingeblendet, sobald der Cursor auf einem Symbol liegt."
L["Inspect data received for %s..."] = "Betrachtungsdaten für %s empfangen..."
L["Leave Arena"] = "Arena verlassen"
L["MainTargetIndicator:UpdateMainTarget(): Usage MainTargetIndicator:UpdateMainTarget(team)"] = "MainTargetIndicator:UpdateMainTarget(): Usage MainTargetIndicator:UpdateMainTarget(team)"
L["Sending inspect query for %s (%s)..."] = "Sende Betrachtungsanfrage für %s (%s)..."
L["Shows the War Game Menu"] = "Zeigt das Menü für Kräftemessen"
L["Shows this info message."] = "Zeigt diese Nachricht"
L["Show Tooltip"] = "Tooltip anzeigen"
L["Spectator addon has been loaded successfully! Type /alspec to open the spectator war game menu or /alspec help for a list of available commands."] = "Zuschaueraddon erfolgreich geladen! Schreibe /alspec, um das Menü für beobachtetes Kräftemessen zu öffnen oder /alspec help für eine Liste an verfügbaren Kommandos."
L["%s: %s"] = "%s: %s"
L["Time in CC:"] = "Zeit im CC:"
L["WARNING! Couldn't register addon message prefix for ArenaLive [Spectator]. You won't be able to receive broadcast data during this session."] = "WARNUNG! Konnte das Addon-Nachrichten-Prefix für ArenaLive [Spectator] nicht registrieren. Du wirst nicht in der Lage sein, gesendete Daten während dieser Session zu erhalten."